#!/bin/bash
# Athena Demo - Synchronized Terminal Script
export TERM=xterm-256color
cd /root/projects/glm-code

clear
echo ""
echo "  ╔══════════════════════════════════════════════════════════════╗"
echo "  ║  A T H E N A — Web3 Smart Contract Security Audit Agent    ║"
echo "  ║  Powered by GLM-5.1 Long-Horizon Task                     ║"
echo "  ╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Model:     GLM-5.1 (200K context, long-horizon reasoning)"
echo "  Pipeline:  8-step audit with subagent parallel orchestration"
echo "  Tools:     13 MCP tools"
echo "  Chains:    Sepolia + Base Sepolia"
echo ""
sleep 9.5

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 1/8] 读取审计 Skill — 12 Agent 并行架构"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > cat skills/glm-audit-skill/SKILL.md"
echo ""
echo "  [OK] Athena — Parallelized Smart Contract Security Audit"
echo "       12 specialized agents running in parallel:"
echo "       ├── Access Control Agent"
echo "       ├── Reentrancy Agent"
echo "       ├── Flash Loan Agent"
echo "       ├── Oracle Manipulation Agent"
echo "       └── ... (8 more specialized agents)"
echo ""
sleep 16

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 2/8] 选择审计目标 — VulnerableBank"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > cat contracts/test-cases/Reentrancy.sol"
echo ""
echo "  contract VulnerableBank {"
echo "      mapping(address => uint256) public balances;"
echo "      function withdraw() public {"
echo "          uint256 balance = balances[msg.sender];"
echo "          (bool success, ) = msg.sender.call{value: balance}();"
echo "          // BUG: state update AFTER external call"
echo "          balances[msg.sender] = 0;"
echo "      }"
echo "  }"
echo ""
echo "  [VULN] Reentrancy: state update AFTER external call"
echo ""
sleep 12

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 3/8] 调度 3 个 Subagent 并行执行"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  Spawning subagents..."
echo ""
echo "    ├─ subagent-1: 静态分析 (Slither + Aderyn)"
echo "    ├─ subagent-2: PoC 生成"
echo "    └─ subagent-3: Fuzz 测试"
echo ""
sleep 11

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 4/8] Subagent 1 — 双引擎静态分析"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > slither contracts/test-cases/Reentrancy.sol"
echo ""
echo "  [HIGH]  reentrancy-eth: Reentrancy in VulnerableBank.withdraw()"
echo "         External call before state update at line 25"
echo "  [LOW]   solc-version: Unspecific pragma version"
echo "  [INFO]  low-level-calls: Low-level call usage"
echo ""
echo "  > aderyn contracts/test-cases/"
echo ""
echo "  [HIGH]  H-3: Reentrancy — State change after external call"
echo "  [HIGH]  H-2: ETH transferred without address checks"
echo "  [LOW]   L-19: Unspecific Solidity Pragma"
echo "  [LOW]   L-21: Public Function Not Used Internally"
echo ""
echo "  [MERGE] Slither (3) + Aderyn (4) → 4 unique findings after dedup"
echo ""
sleep 17.3

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 5/8] Subagent 2 — PoC 攻击验证"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > python3 mcp/tools/poc_generator.py --vuln reentrancy"
echo ""
echo "  contract Attacker {"
echo "      VulnerableBank public bank;"
echo "      function attack() external payable {"
echo "          bank.deposit{value: 1 ether}();"
echo "          bank.withdraw();  // triggers reentrancy"
echo "      }"
echo "      receive() external payable {"
echo "          if (address(bank).balance >= 1 ether)"
echo "              bank.withdraw();  // re-enter"
echo "      }"
echo "  }"
echo ""
echo "  [OK] PoC generated → contracts/test-cases/ReentrancyAttack.sol"
echo ""
sleep 12.5

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 6/8] Subagent 3 — Fuzz 测试验证"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > forge test --match-test testReentrancy -vvv"
echo ""
echo "  [PASS] testFuzz_full_drain()"
echo "  [PASS] testFuzz_reentrancy_steals()"
echo "  [PASS] testFuzz_varying_bank_balance()"
echo "  [PASS] test_attack_counts_reentries()"
echo "  [PASS] test_full_drain()"
echo "  [PASS] test_reentrancy_exploit()"
echo ""
echo "    总测试: 6 | 通过: 6/6 | Fuzz 运行: 768 次"
echo "    银行余额: 10 ETH → 0 ETH | 攻击者获利: 11 ETH"
echo ""
echo "  [VERIFIED] 漏洞通过 fuzz 测试确认"
echo ""
sleep 14.4

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 7/8] 汇总审计结果"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  审计结果汇总:"
echo ""
echo "    静态分析: 4 个唯一发现 (2 HIGH + 2 LOW)"
echo "    PoC 生成: 攻击成功，银行余额被清空"
echo "    Fuzz 测试: 768 次 fuzz 运行，0 反例"
echo ""
echo "    综合评级: S (Critical)"
echo ""
echo "    修复建议:"
echo "      1. 使用 Checks-Effects-Interactions 模式"
echo "      2. 添加 ReentrancyGuard"
echo "      3. 先更新状态，再外部调用"
echo ""
sleep 19.2

clear
echo "────────────────────────────────────────────────────────"
echo "[STEP 8/8] 链上认证 — EAS + NFT"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  > python3 mcp/tools/eas_attest.py --schema 0x6d6520d9..."
echo ""
echo "  [TX]  EAS Attestation created"
echo "       Schema: 0x6d6520d928b6090172a458c2addcd30af1090f5298110e496bb3c9ac3918253e"
echo "       UID:    0xd02800c960f18f0483af4aa320aff314e34c5a83d1c9a9c963b299a88af958b9"
echo ""
echo "  > python3 mcp/tools/evidence_chain.py --mint-nft --grade S"
echo ""
echo "  [TX]  NFT Minted on Sepolia"
echo "       Sepolia:  0x3247d57d37bd1878479f03a077aba807649dbaf5"
echo "       Base:     0xb8f167a84816b5b9373997337119a2186c6e3708"
echo "       Token ID: 1 (Grade S)"
echo "       Traits:   262,144 possible combinations (4^9)"
echo ""
sleep 19

clear
echo "────────────────────────────────────────────────────────"
echo "  MULTI-CHAIN DEPLOYMENT"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  Sepolia:"
echo "    AuditCertificate:  0x3247d57d37bd1878479f03a077aba807649dbaf5"
echo "    AgentEscrowV2:     0x7102b7252dea80529278c8bffc441b96ff24421e"
echo "    ERC7512Metadata:   0x0dd8f8f5b755912aa3b955044d1eff496a65e657"
echo ""
echo "  Base Sepolia:"
echo "    AuditCertificate:  0xb8f167a84816b5b9373997337119a2186c6e3708"
echo "    ERC7512Metadata:   0x5e99f144d3e512f525d24077d4626a064899e177"
echo ""
echo "────────────────────────────────────────────────────────"
echo "  REAL PROTOCOL AUDITS"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  [Audit 1] Curve V2 — Read-Only Reentrancy"
echo "    Severity: CRITICAL | Impact: $70M | Match: 95%"
echo ""
echo "  [Audit 2] Hundred Finance — Reentrancy + Oracle Manipulation"
echo "    Severity: CRITICAL | Impact: $7M | Match: 88%"
echo ""
echo "────────────────────────────────────────────────────────"
echo "  ATHENA — From Vulnerability Discovery to On-Chain Certification"
echo "────────────────────────────────────────────────────────"
echo ""
echo "  GitHub:  https://github.com/tiyadegure/Athena"
echo "  Landing: https://athena.degure.me"
echo "  Model:   GLM-5.1 (Z.AI Coding Plan)"
echo ""
sleep 5
